# Generated by Django 3.2 on 2021-11-11 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('tipo_documento', models.CharField(choices=[('01', 'DNI'), ('03', 'CE'), ('02', 'Pasaporte'), ('04', 'Cédula de identidad')], default='01', max_length=2, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=15, verbose_name='Número de documento')),
                ('sexo', models.CharField(choices=[('2', 'Femenino'), ('1', 'Masculino')], max_length=2, verbose_name='Sexo')),
                ('nombres', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido materno')),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator()])),
                ('cargo_miembro', models.CharField(blank=True, choices=[('presidente', 'Presidente'), ('miembro1', 'Miembro 1'), ('miembro2', 'Miembro 2')], max_length=25, null=True)),
                ('tipo_persona', models.CharField(choices=[('participante', 'Participante'), ('consejo_facultad', 'Miembro del CCEAD Facultad'), ('consejo_unasam', 'Miembro del CCEAD UNASAM')], default='participante', max_length=25)),
                ('es_activo', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.facultad')),
            ],
            options={
                'ordering': ['apellido_paterno'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='Firmante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('unasam', 'UNASAM'), ('facultad', 'Facultad')], max_length=25)),
                ('firma', models.TextField()),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.facultad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
        ),
    ]
