# Generated by Django 3.2 on 2022-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='grado_academico',
            field=models.CharField(blank=True, choices=[('bachiller', 'BACHILLER'), ('licenciado_titulo', 'LICENCIADO/TÍTULO'), ('magister', 'MAGISTER'), ('doctorado', 'DOCTORADO'), ('PhD', 'PhD (philosophie doctor)'), ('tecnico', 'TÉCNICO'), ('sin_grado', 'SIN GRADO')], max_length=25, null=True),
        ),
    ]
