# Generated by Django 3.2 on 2021-11-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('ruta_acta_pdf', models.FileField(blank=True, null=True, upload_to='actas')),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion_horario', models.CharField(blank=True, max_length=250, null=True)),
                ('canal_reunion', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiarios', models.CharField(blank=True, max_length=100, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=250, null=True)),
                ('certificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('ruta_proyecto_pdf', models.FileField(blank=True, null=True, upload_to='proyectos')),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('observacion_revision', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_emision_certificado', models.CharField(choices=[('certificado_unico', 'Certificado único'), ('certificado_por_modulo', 'Certificados por módulos'), ('certificado_unico_y_modulos', 'Certificado único y por módulos')], max_length=45)),
                ('ambito', models.CharField(choices=[('unasam', 'UNASAM'), ('facultad', 'Facultad')], default='facultad', max_length=25)),
                ('se_envio_correo', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('validado', 'Validado'), ('cancelado', 'Cancelado'), ('culminado', 'Culminado'), ('observado', 'Observado'), ('por_validar', 'Por validar')], default='registrado', max_length=25)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.facultad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('estado', models.CharField(choices=[('validado', 'Validado'), ('cancelado', 'Cancelado'), ('culminado', 'Culminado'), ('observado', 'Observado'), ('por_validar', 'Por validar')], max_length=25)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('horas_academicas', models.PositiveIntegerField()),
                ('temas', models.TextField(max_length=1000)),
                ('se_envio_correo', models.BooleanField(default=False)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacion')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRevisionConsejo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('unasam', 'UNASAM'), ('facultad', 'Facultad')], max_length=25)),
                ('cargo_miembro', models.CharField(choices=[('presidente', 'Presidente'), ('miembro1', 'Miembro 1'), ('miembro2', 'Miembro 2')], max_length=25)),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.facultad')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.historialrevision')),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_evidencia_pdf', models.FileField(blank=True, null=True, upload_to='evidencia_capacitacion')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('acta_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.actaasistencia')),
            ],
        ),
        migrations.CreateModel(
            name='CertEmitido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('tipo', models.CharField(choices=[('certificado_unico', 'Certificado único'), ('certificado_por_modulo', 'Certificado por módulo')], default='certificado_unico', max_length=45)),
                ('cargo', models.CharField(choices=[('ponente', 'Ponente'), ('organizador', 'Organizador'), ('responsable', 'Responsable'), ('asistente', 'Asistente')], max_length=25)),
                ('correlativo', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=25)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.modulo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='actaasistencia',
            name='modulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.modulo'),
        ),
        migrations.CreateModel(
            name='ResponsableFirma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('director', 'Director'), ('coordinador', 'Coordinador'), ('ponente', 'Ponente'), ('organizador', 'Organizador')], max_length=45)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacion')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.firmante')),
            ],
            options={
                'unique_together': {('tipo_firma', 'firmante', 'capacitacion')},
            },
        ),
        migrations.CreateModel(
            name='NotaParticipante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=25, null=True)),
                ('acta_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.actaasistencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'unique_together': {('acta_asistencia', 'persona')},
            },
        ),
        migrations.CreateModel(
            name='EquipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ponente', 'Ponente'), ('organizador', 'Organizador'), ('responsable', 'Responsable')], max_length=25)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'unique_together': {('cargo', 'persona', 'capacitacion')},
            },
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'P'), ('F', 'F')], max_length=10)),
                ('acta_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.actaasistencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'unique_together': {('fecha', 'persona', 'acta_asistencia')},
            },
        ),
    ]
