# Generated by Django 3.2 on 2022-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablefirma',
            name='tipo_firma',
            field=models.CharField(choices=[('director', 'DIRECTOR'), ('vicerrector_academico', 'VICERRECTOR ACADÉMICO'), ('presidente_ccead', 'PRESIDENTE CCEAD'), ('coordinador', 'COORDINADOR'), ('ponente', 'PONENTE'), ('organizador', 'ORGANIZADOR')], max_length=45),
        ),
    ]
