# Generated by Django 3.2 on 2022-06-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_alter_responsablefirma_tipo_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
