# Generated by Django 3.2 on 2022-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0003_alter_modulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='nombre',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='objetivo',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='temas',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
